// Pattern: swell dominating over local wind waves.
//
// Visible cue: significant wave height on Windy's waves/swell layers while
// surface wind is light — the waves aren't from local wind.
// Trigger layers: 'waves', 'swell1', 'swell2'.
//
// Mechanism: swell is generated by distant storms and propagates outward as
// long-period waves. It can travel thousands of kilometres, outlasting and
// outrunning its source. When local wind is calm but waves are big, almost
// all the energy arrived from far away.
//
// Detection: marine data available AND swell_wave_height ≥ 1.0m AND
// surface wind ≤ 20 km/h (ruling out locally driven seas).
// Confidence weights swell height and wind weakness.

import type { DetectContext, Facts, PatternModule, WindyOverlay } from '../types';

interface Params {
    swellHeightM: number;
    swellPeriodS: number | null;
    windSpeedKmh: number;
}

function detect(facts: Facts, _ctx: DetectContext) {
    const m = facts.marine;
    if (!m) return { active: false, confidence: 0, params: null as any };

    const swellH = m.swell_wave_height ?? 0;
    const wind = facts.surface.wind_speed_kmh ?? 999;

    const bigSwell = swellH >= 1.0;
    const lightWind = wind <= 20;

    const active = bigSwell && lightWind;

    let confidence = 0;
    if (bigSwell)    confidence += 0.4;
    if (swellH >= 2.0) confidence += 0.2;
    if (swellH >= 3.0) confidence += 0.1;
    if (lightWind)   confidence += 0.2;
    if (wind <= 10)  confidence += 0.1;
    confidence = Math.min(confidence, 1);

    return {
        active,
        confidence,
        params: {
            swellHeightM: Math.round(swellH * 10) / 10,
            swellPeriodS: m.swell_wave_period,
            windSpeedKmh: Math.round(wind),
        } satisfies Params,
    };
}

function visual(_map: any, _facts: Facts, _params: Params): () => void {
    return () => {};
}

function content(_facts: Facts, p: Params) {
    const swellH = p.swellHeightM.toFixed(1);
    const periodPhrase = p.swellPeriodS != null
        ? ` with a ${Math.round(p.swellPeriodS)}-second period`
        : '';

    return {
        title: 'Why there are waves here with little wind',
        mechanism:
            `The dominant signal here is swell — ${swellH}m${periodPhrase}, ` +
            `generated by a distant storm rather than local wind. ` +
            `Swell can travel thousands of kilometres, outlasting and outrunning the storm that created it. ` +
            `When wind is light but waves are big, the energy you're feeling started somewhere far away.`,
        checkNext: [
            {
                label: 'Toggle Wind: look 1000–3000 km upwind for the source storm',
                overlay: 'wind' as WindyOverlay,
            },
            {
                label: 'Toggle Swell: isolate the long-period swell from local wind chop',
                overlay: 'swell1' as WindyOverlay,
            },
        ],
        remember:
            "Windy's Waves layer shows significant wave height — wind sea and swell combined. " +
            'The Swell sublayer isolates the long-period signal. Individual waves can reach roughly twice the significant height.',
    };
}

const swell_vs_wind: PatternModule<Params> = {
    id: 'swell_vs_wind',
    appliesToLayers: ['waves', 'swell1', 'swell2'],
    detect,
    visual,
    content,
};

export default swell_vs_wind;
